//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVC2Test.Domain
{
    public partial class Author
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual string Surname
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Content> Contents
        {
            get
            {
                if (_contents == null)
                {
                    var newCollection = new FixupCollection<Content>();
                    newCollection.CollectionChanged += FixupContents;
                    _contents = newCollection;
                }
                return _contents;
            }
            set
            {
                if (!ReferenceEquals(_contents, value))
                {
                    var previousValue = _contents as FixupCollection<Content>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupContents;
                    }
                    _contents = value;
                    var newValue = value as FixupCollection<Content>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupContents;
                    }
                }
            }
        }
        private ICollection<Content> _contents;

        #endregion
        #region Association Fixup
    
        private void FixupContents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Content item in e.NewItems)
                {
                    item.Author = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Content item in e.OldItems)
                {
                    if (ReferenceEquals(item.Author, this))
                    {
                        item.Author = null;
                    }
                }
            }
        }

        #endregion
    }
}
