//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MVC2Test.Domain
{
    public partial class Content
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string StandFirst
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Author Author
        {
            get { return _author; }
            set
            {
                if (!ReferenceEquals(_author, value))
                {
                    var previousValue = _author;
                    _author = value;
                    FixupAuthor(previousValue);
                }
            }
        }
        private Author _author;

        #endregion
        #region Association Fixup
    
        private void FixupAuthor(Author previousValue)
        {
            if (previousValue != null && previousValue.Contents.Contains(this))
            {
                previousValue.Contents.Remove(this);
            }
    
            if (Author != null)
            {
                if (!Author.Contents.Contains(this))
                {
                    Author.Contents.Add(this);
                }
            }
        }

        #endregion
    }
}
